import { Test, TestingModule } from '@nestjs/testing';
import { ClaudeHooksService } from './claude-hooks.service.js';
import { SessionsService } from '../sessions/sessions.service.js';
import { WorktreeContextService } from '../worktree-context/worktree-context.service.js';
import { SessionTitleService } from '../session-title/session-title.service.js';

describe('ClaudeHooksService', () => {
  let service: ClaudeHooksService;
  let sessionsService: {
    findOne: jest.Mock;
    markCompletionUnreviewed: jest.Mock;
    markLastStateChange: jest.Mock;
    renameFromGeneratedTitle: jest.Mock;
    updateClaudeSessionId: jest.Mock;
  };
  let worktreeContextService: {
    consumeForSession: jest.Mock;
    generate: jest.Mock;
    getCachedSnapshot: jest.Mock;
  };
  let sessionTitleService: {
    generate: jest.Mock;
    isAutoGeneratedName: jest.Mock;
  };

  beforeEach(async () => {
    sessionsService = {
      findOne: jest.fn(),
      markCompletionUnreviewed: jest.fn(),
      markLastStateChange: jest.fn(),
      renameFromGeneratedTitle: jest.fn(),
      updateClaudeSessionId: jest.fn(),
    };
    worktreeContextService = {
      consumeForSession: jest.fn(),
      generate: jest.fn(),
      getCachedSnapshot: jest.fn(),
    };
    sessionTitleService = {
      generate: jest.fn(),
      isAutoGeneratedName: jest.fn((name: string | null | undefined) =>
        typeof name === 'string' && /^Session \d+$/.test(name.trim()),
      ),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        ClaudeHooksService,
        { provide: SessionsService, useValue: sessionsService },
        { provide: WorktreeContextService, useValue: worktreeContextService },
        { provide: SessionTitleService, useValue: sessionTitleService },
      ],
    }).compile();

    service = module.get(ClaudeHooksService);
  });

  it('marks a session unreviewed when running transitions to idle', async () => {
    await service.updateStatus(1, 'running');
    await service.updateStatus(1, 'idle');

    expect(sessionsService.markLastStateChange).toHaveBeenCalledTimes(2);
    expect(sessionsService.markCompletionUnreviewed).toHaveBeenCalledWith(
      1,
      'completed',
    );
  });

  it('marks a session unreviewed when waiting transitions to idle', async () => {
    await service.updateStatus(1, 'running');
    await service.updateStatus(1, 'waiting');
    await service.updateStatus(1, 'idle');

    expect(sessionsService.markLastStateChange).toHaveBeenCalledTimes(3);
    expect(sessionsService.markCompletionUnreviewed).toHaveBeenCalledWith(
      1,
      'completed',
    );
  });

  it('does not mark unreviewed completion for idle without a prior active state', async () => {
    await service.updateStatus(1, 'idle');

    expect(sessionsService.markLastStateChange).toHaveBeenCalledTimes(1);
    expect(sessionsService.markCompletionUnreviewed).not.toHaveBeenCalled();
  });

  it('does not persist a timestamp for duplicate statuses', async () => {
    await service.updateStatus(1, 'running');
    await service.updateStatus(1, 'running');

    expect(sessionsService.markLastStateChange).toHaveBeenCalledTimes(1);
  });

  it('ignores waiting when there was no prior running status', async () => {
    await service.updateStatus(1, 'waiting');

    expect(sessionsService.markLastStateChange).not.toHaveBeenCalled();
    expect(sessionsService.markCompletionUnreviewed).not.toHaveBeenCalled();
  });

  it('sets a running session back to idle on interrupt without marking completion', async () => {
    await service.updateStatus(1, 'running');
    await service.handleInterrupt(1);

    expect(service.getStatus(1)).toBe('idle');
    expect(sessionsService.markLastStateChange).toHaveBeenCalledTimes(2);
    expect(sessionsService.markCompletionUnreviewed).not.toHaveBeenCalled();
  });

  it('ignores duplicate interrupts while already idle', async () => {
    await service.handleInterrupt(1);
    await service.handleInterrupt(1);

    expect(service.getStatus(1)).toBe('idle');
    expect(sessionsService.markLastStateChange).toHaveBeenCalledTimes(1);
    expect(sessionsService.markCompletionUnreviewed).not.toHaveBeenCalled();
  });

  it('stores the Claude session id when SessionStart arrives', async () => {
    await service.handleHookEvent(42, {
      hook_event_name: 'SessionStart',
      session_id: 'claude-session-1',
      source: 'startup',
    });

    expect(sessionsService.updateClaudeSessionId).toHaveBeenCalledWith(
      42,
      'claude-session-1',
    );
    expect(sessionsService.markLastStateChange).not.toHaveBeenCalled();
  });

  it('replaces the stored Claude session id after a manual resume', async () => {
    await service.handleHookEvent(42, {
      hook_event_name: 'SessionStart',
      session_id: 'claude-session-1',
      source: 'startup',
    });
    await service.handleHookEvent(42, {
      hook_event_name: 'SessionStart',
      session_id: 'claude-session-2',
      source: 'resume',
    });

    expect(sessionsService.updateClaudeSessionId).toHaveBeenNthCalledWith(
      1,
      42,
      'claude-session-1',
    );
    expect(sessionsService.updateClaudeSessionId).toHaveBeenNthCalledWith(
      2,
      42,
      'claude-session-2',
    );
  });

  it('does not overwrite the stored Claude session id when the hook payload omits it', async () => {
    await service.handleHookEvent(42, {
      hook_event_name: 'SessionStart',
      session_id: 'claude-session-1',
      source: 'startup',
    });
    await service.handleHookEvent(42, {
      hook_event_name: 'Stop',
    });

    expect(sessionsService.updateClaudeSessionId).toHaveBeenCalledTimes(1);
    expect(sessionsService.updateClaudeSessionId).toHaveBeenCalledWith(
      42,
      'claude-session-1',
    );
  });

  it('emits raw hook events for downstream runtime normalization', async () => {
    const listener = jest.fn();
    service.on('hook-event', listener);

    await service.handleHookEvent(9, {
      hook_event_name: 'SubagentStart',
      session_id: 'claude-session-9',
      agent_id: 'agent-1',
      agent_type: 'code-reviewer',
      cwd: '/tmp/project',
    });

    expect(listener).toHaveBeenCalledWith(
      expect.objectContaining({
        sessionId: 9,
        payload: expect.objectContaining({
          hook_event_name: 'SubagentStart',
          agent_id: 'agent-1',
          agent_type: 'code-reviewer',
          cwd: '/tmp/project',
        }),
        timestamp: expect.any(String),
      }),
    );
  });

  it('treats permission request hooks as waiting when a session is already running', async () => {
    await service.updateStatus(5, 'running');
    await service.handleHookEvent(5, {
      hook_event_name: 'PermissionRequest',
      session_id: 'claude-session-5',
    });

    expect(service.getStatus(5)).toBe('waiting');
  });

  it('lets runtime activity take precedence over hook status for UI sessions', async () => {
    await service.updateStatus(5, 'running');

    service.updateRuntimeActivity(5, {
      activityStatus: 'waiting',
      actionKind: 'permission',
      actionLabel: 'Permission needed',
    });

    expect(service.getStatus(5)).toBe('waiting');
    expect(service.getActivity(5)).toEqual({
      activityStatus: 'waiting',
      actionKind: 'permission',
      actionLabel: 'Permission needed',
    });
    expect(service.getAllActivities()[5]).toEqual({
      activityStatus: 'waiting',
      actionKind: 'permission',
      actionLabel: 'Permission needed',
    });
  });

  it('falls back to hook status when runtime activity becomes idle', async () => {
    await service.updateStatus(5, 'running');
    service.updateRuntimeActivity(5, {
      activityStatus: 'waiting',
      actionKind: 'user_input',
      actionLabel: 'Input needed',
    });

    service.updateRuntimeActivity(5, {
      activityStatus: 'idle',
      actionKind: null,
      actionLabel: null,
    });

    expect(service.getActivity(5)).toEqual({
      activityStatus: 'running',
      actionKind: null,
      actionLabel: null,
    });
  });

  it('ignores late hook events after a session is cleared', async () => {
    service.clearStatus(42);

    await service.handleHookEvent(42, {
      hook_event_name: 'Stop',
      session_id: 'claude-session-42',
    });

    expect(sessionsService.updateClaudeSessionId).not.toHaveBeenCalled();
    expect(sessionsService.markLastStateChange).not.toHaveBeenCalled();
  });

  it('does not generate hook output for non-TUI UserPromptSubmit events', async () => {
    const response = await service.handleHookEvent(7, {
      hook_event_name: 'UserPromptSubmit',
      prompt: 'Please ship this change',
    });

    expect(response).toEqual({ continue: true });
    expect(sessionsService.findOne).not.toHaveBeenCalled();
    expect(worktreeContextService.generate).not.toHaveBeenCalled();
    expect(sessionTitleService.generate).not.toHaveBeenCalled();
  });

  it('returns worktree context and a session title for the first TUI prompt', async () => {
    sessionsService.findOne.mockResolvedValue({
      id: 7,
      repoId: 1,
      worktreePath: '/tmp/project',
      name: 'Session 1',
      hasInjectedWorktreeContext: false,
    });
    worktreeContextService.getCachedSnapshot.mockResolvedValue({
      generationStatus: 'idle',
      contextSentence: null,
    });
    worktreeContextService.generate.mockResolvedValue({
      generationStatus: 'ready',
      contextSentence: 'This branch updates TUI session summaries.',
    });
    worktreeContextService.consumeForSession.mockResolvedValue({
      shouldInject: true,
      contextSentence: 'This branch updates TUI session summaries.',
    });
    sessionTitleService.generate.mockResolvedValue('TUI Session Summaries');
    sessionsService.renameFromGeneratedTitle.mockResolvedValue({
      name: 'TUI Session Summaries',
    });

    const response = await service.handleHookEvent(
      7,
      {
        hook_event_name: 'UserPromptSubmit',
        session_id: 'claude-session-7',
        prompt: 'Please ship this change',
      },
      { origin: 'tui' },
    );

    expect(response).toEqual({
      continue: true,
      hookSpecificOutput: {
        hookEventName: 'UserPromptSubmit',
        additionalContext: [
          '<elevenex-worktree-context>',
          'Context for this session: This branch updates TUI session summaries.',
          '</elevenex-worktree-context>',
        ].join('\n'),
        sessionTitle: 'TUI Session Summaries',
      },
    });
    expect(worktreeContextService.generate).toHaveBeenCalledWith(
      1,
      '/tmp/project',
      { provider: 'claude' },
    );
    expect(worktreeContextService.consumeForSession).toHaveBeenCalledWith(
      7,
      true,
      'This branch updates TUI session summaries.',
    );
    expect(sessionsService.renameFromGeneratedTitle).toHaveBeenCalledWith(
      7,
      'TUI Session Summaries',
    );
  });

  it('skips worktree context when the TUI session already consumed it', async () => {
    sessionsService.findOne.mockResolvedValue({
      id: 7,
      repoId: 1,
      worktreePath: '/tmp/project',
      name: 'Session 1',
      hasInjectedWorktreeContext: true,
    });
    sessionTitleService.generate.mockResolvedValue('TUI Session Summaries');
    sessionsService.renameFromGeneratedTitle.mockResolvedValue({
      name: 'TUI Session Summaries',
    });

    const response = await service.handleHookEvent(
      7,
      {
        hook_event_name: 'UserPromptSubmit',
        prompt: 'Please ship this change',
      },
      { origin: 'tui' },
    );

    expect(worktreeContextService.getCachedSnapshot).not.toHaveBeenCalled();
    expect(worktreeContextService.generate).not.toHaveBeenCalled();
    expect(response).toEqual({
      continue: true,
      hookSpecificOutput: {
        hookEventName: 'UserPromptSubmit',
        sessionTitle: 'TUI Session Summaries',
      },
    });
  });

  it('skips worktree context for slash commands while still generating a title', async () => {
    sessionsService.findOne.mockResolvedValue({
      id: 7,
      repoId: 1,
      worktreePath: '/tmp/project',
      name: 'Session 1',
      hasInjectedWorktreeContext: false,
    });
    sessionTitleService.generate.mockResolvedValue('Claude Status Check');
    sessionsService.renameFromGeneratedTitle.mockResolvedValue({
      name: 'Claude Status Check',
    });

    const response = await service.handleHookEvent(
      7,
      {
        hook_event_name: 'UserPromptSubmit',
        prompt: '/status',
      },
      { origin: 'tui' },
    );

    expect(worktreeContextService.getCachedSnapshot).not.toHaveBeenCalled();
    expect(worktreeContextService.generate).not.toHaveBeenCalled();
    expect(sessionTitleService.generate).toHaveBeenCalledWith(
      '/tmp/project',
      '/status',
    );
    expect(response.hookSpecificOutput?.sessionTitle).toBe(
      'Claude Status Check',
    );
  });

  it('coalesces duplicate concurrent UserPromptSubmit hooks for a session', async () => {
    let resolveCached!: (value: unknown) => void;
    const cachedPromise = new Promise((resolve) => {
      resolveCached = resolve;
    });
    sessionsService.findOne.mockResolvedValue({
      id: 7,
      repoId: 1,
      worktreePath: '/tmp/project',
      name: 'Session 1',
      hasInjectedWorktreeContext: false,
    });
    worktreeContextService.getCachedSnapshot.mockReturnValue(cachedPromise);
    worktreeContextService.generate.mockResolvedValue({
      generationStatus: 'ready',
      contextSentence: 'This branch updates TUI session summaries.',
    });
    worktreeContextService.consumeForSession.mockResolvedValue({
      shouldInject: true,
      contextSentence: 'This branch updates TUI session summaries.',
    });
    sessionTitleService.generate.mockResolvedValue('TUI Session Summaries');
    sessionsService.renameFromGeneratedTitle.mockResolvedValue({
      name: 'TUI Session Summaries',
    });

    const first = service.handleHookEvent(
      7,
      {
        hook_event_name: 'UserPromptSubmit',
        prompt: 'Please ship this change',
      },
      { origin: 'tui' },
    );
    const second = service.handleHookEvent(
      7,
      {
        hook_event_name: 'UserPromptSubmit',
        prompt: 'Please ship this change',
      },
      { origin: 'tui' },
    );
    await new Promise((resolve) => setImmediate(resolve));
    resolveCached({ generationStatus: 'idle', contextSentence: null });

    const [left, right] = await Promise.all([first, second]);

    expect(left).toEqual(right);
    expect(worktreeContextService.getCachedSnapshot).toHaveBeenCalledTimes(1);
    expect(sessionTitleService.generate).toHaveBeenCalledTimes(1);
  });

  it('returns an empty hook response when summary generation fails', async () => {
    sessionsService.findOne.mockResolvedValue({
      id: 7,
      repoId: 1,
      worktreePath: '/tmp/project',
      name: 'Session 1',
      hasInjectedWorktreeContext: false,
    });
    worktreeContextService.getCachedSnapshot.mockRejectedValue(
      new Error('context failed'),
    );
    sessionTitleService.generate.mockRejectedValue(new Error('title failed'));

    await expect(
      service.handleHookEvent(
        7,
        {
          hook_event_name: 'UserPromptSubmit',
          prompt: 'Please ship this change',
        },
        { origin: 'tui' },
      ),
    ).resolves.toEqual({ continue: true });
  });
});
