/* Async mocks intentionally implement the native promise API without I/O. */
/* eslint-disable @typescript-eslint/require-await */
import { EventEmitter } from 'node:events';
import { OpenCodeAgentRuntimeProvider } from './opencode-agent-runtime.provider.js';
import { OpenCodeServer } from './opencode-server.js';
import type { OpenCodeClient } from './opencode-client.js';
import type { Event, Message, Part } from '@opencode-ai/sdk/v2/client';
import type { SessionsService } from '../sessions/sessions.service.js';
import type { SettingsService } from '../settings/settings.service.js';
import type { ClaudeHooksService } from '../claude-hooks/claude-hooks.service.js';
import type { SessionTitleService } from '../session-title/session-title.service.js';
import type { OpenCodeCatalogService } from './opencode-catalog.service.js';
import type { McpAgentTokenService } from '../mcp/identity/mcp-agent-token.service.js';
import type { ClaudeRuntimeEvent } from '../claude-runtime/claude-runtime.types.js';

jest.mock('./opencode-server.js', () => ({ OpenCodeServer: jest.fn() }));
const tick = () => new Promise<void>((resolve) => setImmediate(resolve));
function deferred<T>() {
  let resolve!: (value: T) => void;
  const promise = new Promise<T>((done) => {
    resolve = done;
  });
  return { resolve, promise };
}

function fixture(nativeSessionId = '-1') {
  const events: Event[] = [
    { id: 'connected', type: 'server.connected', properties: {} },
  ];
  let notify = () => {};
  const messages: { info: Message; parts: Part[] }[] = [];
  let savedId = nativeSessionId;
  const turn = deferred<{ data: undefined }>();
  const client = {
    event: {
      subscribe: jest.fn(
        async (_input: unknown, options: { signal: AbortSignal }) => ({
          stream: (async function* () {
            while (!options.signal.aborted) {
              if (!events.length)
                await new Promise<void>((resolve) => {
                  notify = resolve;
                  options.signal.addEventListener('abort', resolve, {
                    once: true,
                  });
                });
              while (events.length) yield events.shift()!;
            }
          })(),
        }),
      ),
    },
    session: {
      create: jest.fn(async () => ({ data: { id: 's' } })),
      prompt: jest.fn(() => turn.promise),
      messages: jest.fn(async () => ({ data: messages })),
      get: jest.fn(async () => ({ data: { id: 's' } })),
      status: jest.fn(async () => ({ data: {} })),
      abort: jest.fn(async () => {
        turn.resolve({ data: undefined });
        return { data: true };
      }),
      update: jest.fn(async () => ({ data: {} })),
      children: jest.fn(async () => ({ data: [] })),
      deleteMessage: jest.fn(async () => ({ data: true })),
    },
    permission: {
      list: jest.fn(async () => ({ data: [] })),
      reply: jest.fn(async () => ({ data: true })),
    },
    question: {
      list: jest.fn(async () => ({ data: [] })),
      reply: jest.fn(async () => ({ data: true })),
      reject: jest.fn(async () => ({ data: true })),
    },
    provider: {
      list: jest.fn(async () => ({
        data: { all: [], connected: [], default: {} },
      })),
    },
    config: { get: jest.fn(async () => ({ data: {} })) },
    global: { health: jest.fn(async () => ({ data: { version: '2' } })) },
    command: { list: jest.fn(async () => ({ data: [] })) },
  };
  const server = Object.assign(new EventEmitter(), {
    start: jest.fn(async () => client as unknown as OpenCodeClient),
    close: jest.fn(),
  });
  (OpenCodeServer as jest.Mock).mockImplementation(() => server);
  const sessions = {
    findOne: jest.fn(async (id: number) => ({
      id,
      surface: 'session',
      worktreePath: '/tmp/repo',
      opencodeSessionId: savedId,
      planMode: false,
      name: 'Named',
    })),
    updateOpenCodeSessionId: jest.fn(async (_id: number, id: string) => {
      savedId = id;
    }),
    markCompletionUnreviewed: jest.fn(async () => {}),
    updatePlanMode: jest.fn(async () => {}),
  };
  const catalog = Object.assign(new EventEmitter(), {
    getModelCatalog: jest.fn(async () => ({
      models: [],
      providerDefaultModelId: null,
    })),
    getAuthStatus: jest.fn(async () => ({ authenticated: true })),
    models: new Map(),
  });
  const provider = new OpenCodeAgentRuntimeProvider(
    sessions as unknown as SessionsService,
    {
      getAgentProviderDefaults: () => ({ model: null, reasoningEffort: null }),
    } as SettingsService,
    { updateRuntimeActivity: jest.fn() } as unknown as ClaudeHooksService,
    { isAutoGeneratedName: () => false } as SessionTitleService,
    catalog as unknown as OpenCodeCatalogService,
    {} as McpAgentTokenService,
  );
  provider.onModuleInit();
  return {
    provider,
    client,
    server,
    sessions,
    turn,
    messages,
    send(event: Event) {
      events.push(event);
      notify();
    },
  };
}

describe('OpenCode runtime lifecycle', () => {
  afterEach(() => jest.clearAllMocks());
  it('drains prompts queued behind a native turn recovered after restart', async () => {
    const f = fixture('s');
    Object.assign(f.client.session, {
      status: async () => ({ data: { s: { type: 'busy' } } }),
    });
    try {
      await f.provider.getHistory(1);
      await f.provider.submitPrompt(1, 'queued behind recovered execution');
      expect(f.client.session.prompt).not.toHaveBeenCalled();
      f.send({
        id: 'idle',
        type: 'session.status',
        properties: { sessionID: 's', status: { type: 'idle' } },
      });
      await tick();
      expect(f.client.session.prompt).toHaveBeenCalledTimes(1);
      expect((await f.provider.getRuntimeState(1)).pendingPrompts).toEqual([]);
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it('does not report success after a native execution failure', async () => {
    const f = fixture();
    try {
      await f.provider.submitPrompt(1, 'first');
      await tick();
      f.send({
        id: 'error',
        type: 'session.error',
        properties: {
          sessionID: 's',
          error: {
            name: 'UnknownError',
            data: { message: 'Execution failed' },
          },
        },
      });
      await tick();
      f.turn.resolve({ data: undefined });
      await tick();
      expect(f.sessions.markCompletionUnreviewed).not.toHaveBeenCalled();
      expect((await f.provider.getRuntimeState(1)).runPhase).toBe('error');
      await f.provider.submitPrompt(1, 'retry');
      await tick();
      expect(f.client.session.prompt).toHaveBeenCalledTimes(2);
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it('coalesces stops and pauses prompts arriving while native abort is pending', async () => {
    const f = fixture();
    const aborted = deferred<{ data: boolean }>();
    f.client.session.abort.mockImplementation(() => aborted.promise);
    try {
      await f.provider.submitPrompt(1, 'first');
      await tick();
      const stopping = f.provider.interrupt(1);
      expect(f.provider.interrupt(1)).toBe(stopping);
      f.turn.resolve({ data: undefined });
      await tick();
      await f.provider.submitPrompt(1, 'arrived while stopping');
      expect(f.client.session.prompt).toHaveBeenCalledTimes(1);
      aborted.resolve({ data: true });
      await stopping;
      expect(await f.provider.getRuntimeState(1)).toMatchObject({
        queuePaused: true,
        pendingPrompts: [{ prompt: 'arrived while stopping' }],
      });
      expect(f.client.session.abort).toHaveBeenCalledTimes(1);
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it('takes a fresh completed snapshot when reconnect recovery overlaps turn completion', async () => {
    const f = fixture();
    const recovery = deferred<{ data: { info: Message; parts: Part[] }[] }>();
    f.client.session.messages.mockImplementationOnce(() => recovery.promise);
    try {
      await f.provider.submitPrompt(1, 'hello');
      await tick();
      f.send({ id: 'reconnect', type: 'server.connected', properties: {} });
      await tick();
      f.turn.resolve({ data: undefined });
      f.messages.push({
        info: {
          id: 'user',
          role: 'user',
          agent: 'build',
          time: { created: 1 },
        } as Message,
        parts: [
          {
            id: 'text',
            messageID: 'user',
            sessionID: 's',
            type: 'text',
            text: 'hello',
          },
        ],
      });
      recovery.resolve({ data: [] });
      await tick();
      expect(
        (await f.provider.getHistory(1)).map((item) => item.content),
      ).toEqual(['hello']);
      expect(f.client.session.messages).toHaveBeenCalledTimes(2);
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it.each(['stop', 'clear', 'cancel'])(
    'accepts fresh prompts after %s leaves an empty queue',
    async (action) => {
      const f = fixture();
      try {
        await f.provider.submitPrompt(1, 'first');
        await tick();
        if (action !== 'stop') await f.provider.submitPrompt(1, 'queued');
        await f.provider.interrupt(1);
        if (action === 'clear') await f.provider.clearPendingPrompts(1);
        if (action === 'cancel') {
          const queued = (await f.provider.getRuntimeState(1))
            .pendingPrompts[0];
          await f.provider.cancelPendingPrompt(1, queued.id);
        }
        expect((await f.provider.getRuntimeState(1)).queuePaused).toBe(false);
        await f.provider.submitPrompt(1, 'fresh');
        await tick();
        expect(f.client.session.prompt).toHaveBeenCalledTimes(2);
        expect((await f.provider.getRuntimeState(1)).pendingPrompts).toEqual(
          [],
        );
      } finally {
        f.provider.onModuleDestroy();
      }
    },
  );
  it('publishes recovered history and replaces stale live content without repeated history reads', async () => {
    const f = fixture();
    const emitted: ClaudeRuntimeEvent[] = [];
    f.provider.on('event', (event: ClaudeRuntimeEvent) => emitted.push(event));
    try {
      await f.provider.submitPrompt(1, 'first');
      await tick();
      const info: Message = {
        id: 'm',
        sessionID: 's',
        role: 'user',
        agent: 'build',
        model: { providerID: 'test', modelID: 'model' },
        time: { created: 1 },
      };
      const part: Part = {
        id: 'p',
        sessionID: 's',
        messageID: 'm',
        type: 'text',
        text: 'before disconnect',
      };
      f.send({ id: 'm', type: 'message.updated', properties: { info } });
      f.send({ id: 'p', type: 'message.part.updated', properties: { part } });
      await tick();
      f.messages.push({
        info,
        parts: [{ ...part, text: 'recovered full content' }],
      });
      f.send({ id: 'reconnect', type: 'server.connected', properties: {} });
      await tick();
      const recovered = emitted
        .filter((event) => event.type === 'history_snapshot')
        .at(-1);
      expect(recovered?.payload.history).toMatchObject([
        { content: 'recovered full content' },
      ]);
      expect((await f.provider.getRuntimeState(1)).liveItems[0].content).toBe(
        'recovered full content',
      );
      const reads = f.client.session.messages.mock.calls.length;
      await Promise.all([
        f.provider.getHistory(1),
        f.provider.getSnapshot(1),
        f.provider.getHistory(1),
      ]);
      expect(f.client.session.messages).toHaveBeenCalledTimes(reads);
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it('emits bounded deltas after a single text baseline', async () => {
    const f = fixture();
    const emitted: ClaudeRuntimeEvent[] = [];
    f.provider.on('event', (event: ClaudeRuntimeEvent) => emitted.push(event));
    try {
      await f.provider.submitPrompt(1, 'first');
      await tick();
      f.send({
        id: 'p',
        type: 'message.part.updated',
        properties: {
          part: {
            id: 'p',
            sessionID: 's',
            messageID: 'm',
            type: 'text',
            text: '',
          },
        },
      });
      for (let index = 0; index < 50; index++)
        f.send({
          id: `d${index}`,
          type: 'message.part.delta',
          properties: {
            sessionID: 's',
            messageID: 'm',
            partID: 'p',
            field: 'text',
            delta: 'token',
          },
        });
      await tick();
      expect(
        emitted.filter((event) => event.type === 'message_start'),
      ).toHaveLength(1);
      expect(emitted.filter((event) => event.type === 'message_delta')).toEqual(
        Array.from({ length: 50 }, () => ({
          type: 'message_delta',
          payload: { sessionId: 1, itemId: 'p', delta: 'token' },
        })),
      );
      expect((await f.provider.getRuntimeState(1)).liveItems[0].content).toBe(
        'token'.repeat(50),
      );
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it('follows native v1 plan_exit through its synthetic user message', async () => {
    const f = fixture();
    try {
      await f.provider.setPlanMode(1, true);
      await f.provider.submitPrompt(1, 'plan');
      await tick();
      expect(f.client.session.prompt.mock.calls[0][0]).toMatchObject({
        agent: 'plan',
      });
      f.send({
        id: 'plan-exit',
        type: 'message.updated',
        properties: {
          info: {
            id: 'synthetic',
            sessionID: 's',
            role: 'user',
            agent: 'build',
            time: { created: 1 },
          } as Message,
        },
      });
      await tick();
      expect((await f.provider.getRuntimeState(1)).planMode).toBe(false);
      expect(f.sessions.updatePlanMode).toHaveBeenLastCalledWith(1, false);
      f.turn.resolve({ data: undefined });
      await tick();
      await f.provider.submitPrompt(1, 'implement');
      await tick();
      expect(f.client.session.prompt.mock.calls[1][0]).toMatchObject({
        agent: 'build',
      });
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it('routes nested approvals and questions even when creation events were missed', async () => {
    const f = fixture();
    Object.assign(f.client.session, {
      get: jest.fn(async ({ sessionID }: { sessionID: string }) => ({
        data: {
          id: sessionID,
          parentID:
            sessionID === 'grandchild'
              ? 'child'
              : sessionID === 'child'
                ? 's'
                : undefined,
          title: sessionID,
          time: { created: 1 },
        },
      })),
    });
    try {
      await f.provider.submitPrompt(1, 'first');
      await tick();
      f.send({
        id: 'nested',
        type: 'permission.asked',
        properties: {
          id: 'nested',
          sessionID: 'grandchild',
          permission: 'read',
          patterns: [],
          metadata: {},
          always: [],
        },
      });
      f.send({
        id: 'form',
        type: 'question.asked',
        properties: {
          id: 'form',
          sessionID: 'grandchild',
          questions: [
            {
              question: 'Continue?',
              header: 'Next',
              options: [{ label: 'Yes', description: 'Continue' }],
            },
          ],
        },
      });
      await tick();
      const state = await f.provider.getRuntimeState(1);
      expect(state.pendingPermissionRequest?.requestId).toBe('nested');
      expect(state.pendingUserInputRequest?.requestId).toBe('form');
      expect(state.subagents.map((agent) => agent.agentId)).toEqual([
        'child',
        'grandchild',
      ]);
      await f.provider.approvePermission(1, 'nested');
      await f.provider.getSubagentHistory(1, 'grandchild');
      expect(f.client.session.messages).toHaveBeenCalledWith({
        sessionID: 'grandchild',
      });
      await expect(
        f.provider.getSubagentHistory(1, 'foreign'),
      ).rejects.toThrow();
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it('streams stable parts, resumes history, and completes a turn without duplicates', async () => {
    const f = fixture();
    try {
      await f.provider.submitPrompt(1, 'hello');
      await tick();
      expect(f.sessions.updateOpenCodeSessionId).toHaveBeenCalledWith(1, 's');
      const info = {
        id: 'm',
        sessionID: 's',
        role: 'assistant',
        time: { created: 1 },
        agent: 'build',
        modelID: 'model',
        providerID: 'test',
        tokens: { input: 10, output: 2, cache: { read: 5, write: 0 } },
      } as Message;
      const part: Part = {
        id: 'p',
        sessionID: 's',
        messageID: 'm',
        type: 'text',
        text: 'Hi',
      };
      f.send({
        id: 'message',
        type: 'message.updated',
        properties: { sessionID: 's', info },
      });
      f.send({
        id: 'part',
        type: 'message.part.updated',
        properties: { sessionID: 's', part, time: 1 },
      });
      f.send({
        id: 'delta',
        type: 'message.part.delta',
        properties: {
          sessionID: 's',
          messageID: 'm',
          partID: 'p',
          field: 'text',
          delta: ' there',
        },
      });
      await tick();
      expect((await f.provider.getRuntimeState(1)).liveItems).toEqual([
        expect.objectContaining({ id: 'p', content: 'Hi there' }),
      ]);
      f.messages.push({ info, parts: [{ ...part, text: 'Hi there' }] });
      f.turn.resolve({ data: undefined });
      await tick();
      await tick();
      expect(
        (await f.provider.getSnapshot(1)).history.map((item) => item.content),
      ).toEqual(['Hi there']);
      const snapshot = await f.provider.getSnapshot(1);
      expect(snapshot.canInterrupt).toBe(false);
      expect(snapshot.contextUsage).toMatchObject({
        model: 'test/model',
        totalTokens: 17,
      });
      expect(f.sessions.markCompletionUnreviewed).toHaveBeenCalledTimes(1);
      expect(f.client.session.children).not.toHaveBeenCalled();
      expect(f.client.permission.list).not.toHaveBeenCalled();
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it('queues prompts, pauses on interruption, and preserves the pending queue', async () => {
    const f = fixture();
    try {
      await f.provider.submitPrompt(1, 'first');
      await tick();
      await f.provider.submitPrompt(1, 'second');
      expect(f.client.session.prompt).toHaveBeenCalledTimes(1);
      await f.provider.interrupt(1);
      const state = await f.provider.getRuntimeState(1);
      expect(state.queuePaused).toBe(true);
      expect(state.pendingPrompts[0].prompt).toBe('second');
      expect(f.sessions.markCompletionUnreviewed).not.toHaveBeenCalled();
      await f.provider.clearPendingPrompts(1);
      expect((await f.provider.getRuntimeState(1)).pendingPrompts).toEqual([]);
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it('handles several pending approvals and refuses another session’s requests', async () => {
    const f = fixture();
    try {
      await f.provider.submitPrompt(1, 'first');
      await tick();
      for (const id of ['a', 'b'])
        f.send({
          id,
          type: 'permission.asked',
          properties: {
            id,
            sessionID: 's',
            permission: 'bash',
            patterns: ['git status'],
            metadata: {},
            always: [],
          },
        });
      f.send({
        id: 'foreign',
        type: 'permission.asked',
        properties: {
          id: 'foreign',
          sessionID: 'other',
          permission: 'bash',
          patterns: [],
          metadata: {},
          always: [],
        },
      });
      await tick();
      expect(
        (await f.provider.getRuntimeState(1)).pendingPermissionRequest
          ?.requestId,
      ).toBe('a');
      await expect(f.provider.approvePermission(1, 'foreign')).rejects.toThrow(
        'no longer pending',
      );
      await f.provider.approvePermission(1, 'a', true);
      expect(f.client.permission.reply).toHaveBeenCalledWith({
        requestID: 'a',
        reply: 'always',
      });
      expect(
        (await f.provider.getRuntimeState(1)).pendingPermissionRequest
          ?.requestId,
      ).toBe('b');
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it('coalesces concurrent startup and releases its server during cleanup', async () => {
    const f = fixture();
    await Promise.all([
      f.provider.getAutocompleteItems(1),
      f.provider.getAutocompleteItems(1),
    ]);
    expect(OpenCodeServer).toHaveBeenCalledTimes(1);
    await f.provider.cleanupSession(1);
    expect(f.server.close).toHaveBeenCalledTimes(1);
    f.provider.onModuleDestroy();
  });
  it('uses native v2 history-only rewind without invoking per-message deletion', async () => {
    const f = fixture();
    const rewindHistory = jest.fn(async () => {});
    Object.assign(f.client, { rewindHistory });
    await f.provider.submitPrompt(1, 'hello');
    await tick();
    f.messages.push({
      info: { id: 'm', role: 'user', time: { created: 1 } } as Message,
      parts: [
        {
          id: 'p',
          messageID: 'm',
          sessionID: 's',
          type: 'text',
          text: 'hello',
        },
      ],
    });
    f.turn.resolve({ data: undefined });
    await tick();
    await tick();
    try {
      await f.provider.rewindConversation(1, 'p');
      expect(rewindHistory).toHaveBeenCalledWith('s', 'm');
      expect(f.client.session.deleteMessage).not.toHaveBeenCalled();
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it('interrupts a session being created without dispatching a late prompt', async () => {
    const f = fixture();
    const creating = deferred<{ data: { id: string } }>();
    f.client.session.create.mockImplementation(() => creating.promise);
    try {
      await f.provider.submitPrompt(1, 'first');
      await tick();
      const interruption = f.provider.interrupt(1);
      await tick();
      creating.resolve({ data: { id: 's' } });
      await interruption;
      expect(f.client.session.prompt).not.toHaveBeenCalled();
      const snapshot = await f.provider.getSnapshot(1);
      expect(snapshot.canInterrupt).toBe(false);
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it('loads project-specific models and preserves the configured default primary agent', async () => {
    const f = fixture();
    Object.assign(f.client.provider, {
      list: async () => ({
        data: {
          connected: ['local'],
          all: [
            {
              id: 'local',
              name: 'Local',
              models: {
                vision: {
                  id: 'vision',
                  name: 'Vision',
                  status: 'active',
                  variants: { custom: {} },
                  capabilities: { input: { image: true } },
                  limit: { context: 10000 },
                },
              },
            },
          ],
        },
      }),
    });
    Object.assign(f.client.config, {
      get: async () => ({ data: { model: 'local/vision' } }),
    });
    Object.assign(f.client, {
      resources: async () => ({
        defaultAgent: 'reviewer',
        agents: [{ id: 'reviewer', name: 'Reviewer', primary: true }],
        skills: [{ id: 'skill', name: 'review' }],
      }),
    });
    try {
      await f.provider.submitPrompt(1, 'hello');
      await tick();
      expect(f.client.session.prompt).toHaveBeenCalledWith(
        expect.objectContaining({
          model: { providerID: 'local', modelID: 'vision' },
          agent: 'reviewer',
        }),
        expect.anything(),
      );
      expect((await f.provider.getRuntimeState(1)).availableModels).toEqual([
        expect.objectContaining({
          id: 'local/vision',
          reasoningEfforts: ['custom'],
        }),
      ]);
      expect(
        (await f.provider.getAutocompleteItems(1)).map((item) => item.label),
      ).toEqual(['agent Reviewer', 'review']);
    } finally {
      f.provider.onModuleDestroy();
    }
  });
  it('recovers pending subagent approvals from native snapshots', async () => {
    const f = fixture();
    Object.assign(f.client.session, {
      children: async () => ({
        data: [{ id: 'child', title: 'Explorer', time: { created: 1 } }],
      }),
    });
    Object.assign(f.client.permission, {
      list: async () => ({
        data: [
          {
            id: 'approval',
            sessionID: 'child',
            permission: 'read',
            patterns: [],
            metadata: {},
            always: [],
          },
        ],
      }),
    });
    try {
      await f.provider.submitPrompt(1, 'hello');
      await tick();
      await f.provider.getHistory(1);
      expect(
        (await f.provider.getRuntimeState(1)).pendingPermissionRequest
          ?.requestId,
      ).toBe('approval');
      await f.provider.approvePermission(1, 'approval');
      expect(f.client.permission.reply).toHaveBeenCalledWith({
        requestID: 'approval',
        reply: 'once',
      });
    } finally {
      f.provider.onModuleDestroy();
    }
  });
});
