export function isAutoGeneratedSessionName(
  name: string | null | undefined,
): boolean {
  return (
    typeof name === 'string' &&
    (/^Session \d+$/.test(name.trim()) || name.trim() === 'Temporary session')
  );
}
