import { Injectable, Logger } from '@nestjs/common';
import { createRequire } from 'module';
import { query, type SDKAssistantMessage } from '@anthropic-ai/claude-agent-sdk';
import { buildAugmentedEnv, findBinary } from '../config/system-paths.js';

const MAX_PROMPT_CHARS = 4000;

@Injectable()
export class SessionTitleService {
  private readonly logger = new Logger(SessionTitleService.name);

  isAutoGeneratedName(name: string | null | undefined): boolean {
    return typeof name === 'string' && /^Session \d+$/.test(name.trim());
  }

  async generate(worktreePath: string, prompt: string): Promise<string | null> {
    const pathToClaudeCodeExecutable =
      this.resolveSdkClaudePath() ?? findBinary('claude') ?? undefined;

    const runtimeQuery = query({
      prompt: [
        'Name this session based on the user\'s first message.',
        'Respond promptly with a broad short title. Do not investigate, browse, inspect files, or dig into details.',
        'Return only the session name, with no quotes, markdown, or commentary.',
        'Rules:',
        '- 3 to 5 words maximum',
        '- summarize the likely overall task broadly',
        '- use title case or compact sentence case',
        '- do not include trailing punctuation',
        '',
        'First message:',
        prompt.slice(0, MAX_PROMPT_CHARS),
      ].join('\n'),
      options: {
        cwd: worktreePath,
        model: 'haiku',
        maxTurns: 1,
        permissionMode: 'plan',
        canUseTool: async () => ({
          behavior: 'deny' as const,
          message: 'Tool use disabled for session title generation',
        }),
        ...(pathToClaudeCodeExecutable ? { pathToClaudeCodeExecutable } : {}),
        systemPrompt: { type: 'preset' as const, preset: 'claude_code' as const },
        tools: { type: 'preset' as const, preset: 'claude_code' as const },
        env: buildAugmentedEnv(process.env, worktreePath),
      },
    });

    let assistantText = '';
    try {
      for await (const message of runtimeQuery) {
        if (message.type === 'assistant') {
          assistantText += this.extractText(message as SDKAssistantMessage);
        }
      }
    } catch (error) {
      this.logger.warn(
        `Title query failed worktreePath=${worktreePath} error=${String(error)} rawReply=${JSON.stringify(assistantText)}`,
      );
      return null;
    } finally {
      runtimeQuery.close();
    }

    const title = this.normalize(assistantText);
    if (title === null) {
      this.logger.warn(
        `Title normalization returned null worktreePath=${worktreePath} rawReply=${JSON.stringify(assistantText)}`,
      );
    }
    return title;
  }

  private extractText(message: SDKAssistantMessage): string {
    const content = Array.isArray(message.message?.content) ? message.message.content : [];
    return content.map((part) => (part.type === 'text' ? part.text : '')).join('');
  }

  private normalize(rawTitle: string): string | null {
    const cleaned = rawTitle
      .replace(/```[\s\S]*?```/g, (block) => block.replace(/```[a-zA-Z]*|```/g, ''))
      .replace(/^[\s"'`*_#>-]+|[\s"'`*_#>-]+$/g, '')
      .replace(/[.!?;:,\s"'`*_#>-]+$/g, '')
      .replace(/\s+/g, ' ')
      .trim();

    if (!cleaned) return null;
    const title = cleaned.split(' ').filter(Boolean).slice(0, 5).join(' ').trim();
    return title || null;
  }

  private resolveSdkClaudePath(): string | null {
    const ext = process.platform === 'win32' ? '.exe' : '';
    const candidates =
      process.platform === 'linux'
        ? [
            `@anthropic-ai/claude-agent-sdk-linux-${process.arch}-musl/claude${ext}`,
            `@anthropic-ai/claude-agent-sdk-linux-${process.arch}/claude${ext}`,
          ]
        : [`@anthropic-ai/claude-agent-sdk-${process.platform}-${process.arch}/claude${ext}`];

    const scopedRequire = createRequire(__filename);
    for (const candidate of candidates) {
      try {
        return scopedRequire.resolve(candidate);
      } catch {
        // Try next candidate.
      }
    }
    return null;
  }
}
