import { Injectable, Logger } from '@nestjs/common';
import { createRequire } from 'module';
import { buildAugmentedEnvAsync, findBinary } from '../config/system-paths.js';

const MAX_PROMPT_CHARS = 4000;
type SDKAssistantMessage =
  import('@anthropic-ai/claude-agent-sdk').SDKAssistantMessage;

@Injectable()
export class SessionTitleService {
  private readonly logger = new Logger(SessionTitleService.name);

  isAutoGeneratedName(name: string | null | undefined): boolean {
    return typeof name === 'string' && /^Session \d+$/.test(name.trim());
  }

  async generate(worktreePath: string, prompt: string): Promise<string | null> {
    const startedAtMs = Date.now();
    const promptLength = prompt.length;
    this.logger.log(
      `Session title generation requested worktreePath=${JSON.stringify(worktreePath)} promptLength=${promptLength} promptTruncated=${promptLength > MAX_PROMPT_CHARS}`,
    );

    const sdk = await this.loadClaudeSdk();
    if (!sdk) {
      this.logger.warn(
        `Session title generation skipped because Claude SDK is unavailable worktreePath=${JSON.stringify(worktreePath)} promptLength=${promptLength}`,
      );
      return null;
    }
    const pathToClaudeCodeExecutable =
      this.resolveClaudeCodeExecutable() ?? undefined;
    let env: NodeJS.ProcessEnv;
    try {
      env = await buildAugmentedEnvAsync(process.env, worktreePath);
    } catch (error) {
      this.logger.warn(
        `Session title environment setup failed worktreePath=${JSON.stringify(worktreePath)} elapsedMs=${Date.now() - startedAtMs} error=${String(error)}`,
      );
      throw error;
    }

    this.logger.debug(
      `Session title query starting worktreePath=${JSON.stringify(worktreePath)} promptLength=${promptLength} claudeExecutable=${JSON.stringify(pathToClaudeCodeExecutable ?? null)} envPathPresent=${Boolean(env.PATH)}`,
    );

    const runtimeQuery = sdk.query({
      prompt: [
        "Name this session based on the user's first message.",
        'Respond immediately with a broad short title from the first message only.',
        'Do not use tools, investigate, browse, inspect files, or dig into details.',
        'Return only the session name, with no quotes, markdown, or commentary.',
        'Rules:',
        '- 3 to 5 words maximum',
        '- summarize the likely overall task broadly',
        '- use title case or compact sentence case',
        '- do not include trailing punctuation',
        '',
        'First message:',
        prompt.slice(0, MAX_PROMPT_CHARS),
      ].join('\n'),
      options: {
        cwd: worktreePath,
        model: 'haiku',
        maxTurns: 1,
        settingSources: [],
        allowedTools: [],
        canUseTool: () =>
          Promise.resolve({
            behavior: 'deny' as const,
            message: 'Tool use disabled for session title generation',
          }),
        ...(pathToClaudeCodeExecutable ? { pathToClaudeCodeExecutable } : {}),
        systemPrompt:
          'You generate concise session titles. Reply with only the title.',
        tools: [],
        env,
      },
    });

    let assistantText = '';
    try {
      for await (const message of runtimeQuery) {
        if (message.type === 'assistant') {
          assistantText += this.extractText(message);
        }
      }
    } catch (error) {
      this.logger.warn(
        `Title query failed worktreePath=${JSON.stringify(worktreePath)} elapsedMs=${Date.now() - startedAtMs} error=${String(error)} rawReply=${JSON.stringify(assistantText)}`,
      );
      return null;
    } finally {
      runtimeQuery.close();
    }

    const title = this.normalize(assistantText);
    if (title === null) {
      this.logger.warn(
        `Title normalization returned null worktreePath=${JSON.stringify(worktreePath)} elapsedMs=${Date.now() - startedAtMs} rawReply=${JSON.stringify(assistantText)}`,
      );
    } else {
      this.logger.log(
        `Session title generated worktreePath=${JSON.stringify(worktreePath)} elapsedMs=${Date.now() - startedAtMs} rawReplyLength=${assistantText.length} title=${JSON.stringify(title)}`,
      );
    }
    return title;
  }

  private extractText(message: SDKAssistantMessage): string {
    const content = Array.isArray(message.message?.content)
      ? message.message.content
      : [];
    return content
      .map((part) => (part.type === 'text' ? part.text : ''))
      .join('');
  }

  private normalize(rawTitle: string): string | null {
    const cleaned = rawTitle
      .replace(/```[\s\S]*?```/g, (block) =>
        block.replace(/```[a-zA-Z]*|```/g, ''),
      )
      .replace(/^[\s"'`*_#>-]+|[\s"'`*_#>-]+$/g, '')
      .replace(/[.!?;:,\s"'`*_#>-]+$/g, '')
      .replace(/\s+/g, ' ')
      .trim();

    if (!cleaned) return null;
    const title = cleaned
      .split(' ')
      .filter(Boolean)
      .slice(0, 5)
      .join(' ')
      .trim();
    return title || null;
  }

  private async loadClaudeSdk(): Promise<{
    query: (typeof import('@anthropic-ai/claude-agent-sdk'))['query'];
  } | null> {
    try {
      return await import('@anthropic-ai/claude-agent-sdk');
    } catch (error) {
      this.logger.warn(`Failed to load Claude SDK: ${String(error)}`);
      return null;
    }
  }

  private resolveSdkClaudePath(): string | null {
    const ext = process.platform === 'win32' ? '.exe' : '';
    const candidates =
      process.platform === 'linux'
        ? [
            `@anthropic-ai/claude-agent-sdk-linux-${process.arch}-musl/claude${ext}`,
            `@anthropic-ai/claude-agent-sdk-linux-${process.arch}/claude${ext}`,
          ]
        : [
            `@anthropic-ai/claude-agent-sdk-${process.platform}-${process.arch}/claude${ext}`,
          ];

    const scopedRequire = createRequire(__filename);
    for (const candidate of candidates) {
      try {
        return scopedRequire.resolve(candidate);
      } catch {
        // Try next candidate.
      }
    }
    return null;
  }

  private resolveClaudeCodeExecutable(): string | null {
    const configuredPath = process.env.ELEVENEX_CLAUDE_BIN?.trim();
    if (configuredPath) {
      return findBinary(configuredPath) ?? configuredPath;
    }

    return this.resolveSdkClaudePath() ?? findBinary('claude');
  }
}
